//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposito
    {
        public int Id { get; set; }
        public System.DateTime FechaDeposito { get; set; }
        public double ImporteDeposito { get; set; }
        public string BancoDeposito { get; set; }
        public string ObservacionesDepositos { get; set; }
        public int idAgencia { get; set; }
    
        public virtual Agencia Agencia { get; set; }
    }
}
